//@version=5
indicator("RSI SMA/EMA")
src = close, 
rsilen = input.int(14, minval=1, title="RSI Length")
smalen = input.int(9, minval=1, maxval=10, title="SMA of RSI Length")
emalen = input.int(39, minval=39, maxval=42, title="EMA of RSI Length") 

smaRSI = ta.sma(ta.rsi(close, rsilen), smalen)
emaRSI = ta.ema(ta.rsi(close, rsilen), emalen)


band2 = hline(85, title="Upper Line for bullish control zone", linestyle=hline.style_solid, linewidth=1,color=color.new(color.black,100))
band3 = hline(67, title="Lower line for bullish control zone", linestyle=hline.style_solid, linewidth=1, color=color.new(color.black,100))
band1 = hline(34, title="Upper line for bearish control zone", linestyle=hline.style_solid, linewidth=1, color=color.new(color.black,100))
band0 = hline(15, title="Lower line for bearish control zone", linestyle=hline.style_solid, linewidth=1, color=color.new(color.black,100))
band4 = hline(38, title="Lower line for bull support zone", linestyle=hline.style_solid, linewidth=1, color=color.new(color.black,100))
band5 = hline(50, title="Upper line for bull support zone", linestyle=hline.style_solid, linewidth=1, color=color.new(color.black,100))
band6 = hline(63, title="Upper line for bearish resistance zone", linestyle=hline.style_solid, linewidth=1, color=color.new(color.black,100))

fill(band1, band0, color=color.new(color.gray,85), title="bearish control zone fill")
fill(band1, band4, color=color.new(color.white,85), title="nomans land zone fill")
fill(band4, band5, color=color.new(color.blue,85), title="bull support zone fill")
fill(band5, band6, color=color.new(color.gray,85), title="bearish resistance zone fill")
fill(band6, band3, color=color.new(color.white,85), title="nomans land zone fill")
fill(band3, band2, color=color.new(color.blue,85), title="bullish resistance zone fill")


plot(ta.rsi(close, rsilen), title="RSI", color=color.new(color.rgb(66,98,251,0), 0), style=plot.style_line, linewidth=1)
plot(smaRSI, title="SMA of RSI", color=color.new(color.black, 0), style=plot.style_line, linewidth=1)
plot(emaRSI, title="EMA of RSI", color=color.new(color.red, 0), style=plot.style_line, linewidth=1)
